// Banco de dados de palavras para o jogo IMPOSTOR.
// Cada categoria possui pares de palavras fortemente relacionadas para que o impostor possa blefar sutilmente.

export const wordCategories = {
  "Alimentos e Bebidas": [
    { civilian: "Pizza", impostor: "Hambúrguer" },
    { civilian: "Café", impostor: "Chá" },
    { civilian: "Cerveja", impostor: "Vinho" },
    { civilian: "Sorvete", impostor: "Picolé" },
    { civilian: "Sushi", impostor: "Sashimi" },
    { civilian: "Chocolate", impostor: "Brigadeiro" },
    { civilian: "Pão", impostor: "Torrada" },
    { civilian: "Arroz", impostor: "Feijão" },
    { civilian: "Maçã", impostor: "Pera" },
    { civilian: "Refrigerante", impostor: "Suco" },
    { civilian: "Queijo", impostor: "Presunto" },
    { civilian: "Coxinha", impostor: "Pastel" },
    { civilian: "Lasanha", impostor: "Macarronada" },
    { civilian: "Bolo", impostor: "Torta" },
    { civilian: "Pipoca", impostor: "Algodão Doce" },
    { civilian: "Leite", impostor: "Iogurte" },
    { civilian: "Melancia", impostor: "Melão" },
    { civilian: "Biscoito", impostor: "Bolacha" },
    { civilian: "Batata Frita", impostor: "Purê de Batata" },
    { civilian: "Pudim", impostor: "Gelatina" }
  ],
  "Animais": [
    { civilian: "Cão", impostor: "Gato" },
    { civilian: "Leão", impostor: "Tigre" },
    { civilian: "Golfinho", impostor: "Baleia" },
    { civilian: "Cavalo", impostor: "Zebra" },
    { civilian: "Águia", impostor: "Gavião" },
    { civilian: "Rato", impostor: "Hamster" },
    { civilian: "Jacaré", impostor: "Crocodilo" },
    { civilian: "Abelha", impostor: "Vespa" },
    { civilian: "Elefante", impostor: "Mamute" },
    { civilian: "Tubarão", impostor: "Arraia" },
    { civilian: "Macaco", impostor: "Gorila" },
    { civilian: "Pinguim", impostor: "Ganso" },
    { civilian: "Cobra", impostor: "Lagarto" },
    { civilian: "Formiga", impostor: "Cupim" },
    { civilian: "Coruja", impostor: "Morcego" },
    { civilian: "Urso", impostor: "Panda" },
    { civilian: "Galinha", impostor: "Pato" },
    { civilian: "Sapo", impostor: "Rã" },
    { civilian: "Ovelha", impostor: "Cabra" },
    { civilian: "Caranguejo", impostor: "Lagosta" }
  ],
  "Lugares e Turismo": [
    { civilian: "Praia", impostor: "Piscina" },
    { civilian: "Cinema", impostor: "Teatro" },
    { civilian: "Escola", impostor: "Faculdade" },
    { civilian: "Hospital", impostor: "Posto de Saúde" },
    { civilian: "Parque", impostor: "Floresta" },
    { civilian: "Shopping", impostor: "Supermercado" },
    { civilian: "Academia", impostor: "Estádio" },
    { civilian: "Aeroporto", impostor: "Rodoviária" },
    { civilian: "Museu", impostor: "Biblioteca" },
    { civilian: "Hotel", impostor: "Pousada" },
    { civilian: "Igreja", impostor: "Templo" },
    { civilian: "Escritório", impostor: "Home Office" },
    { civilian: "Restaurante", impostor: "Lanchonete" },
    { civilian: "Zoológico", impostor: "Aquário" },
    { civilian: "Castelo", impostor: "Palácio" },
    { civilian: "Fazenda", impostor: "Sítio" },
    { civilian: "Cachoeira", impostor: "Rio" },
    { civilian: "Padaria", impostor: "Confeitaria" },
    { civilian: "Montanha", impostor: "Vulcão" },
    { civilian: "Metrô", impostor: "Trem" }
  ],
  "Profissões": [
    { civilian: "Médico", impostor: "Enfermeiro" },
    { civilian: "Bombeiro", impostor: "Policial" },
    { civilian: "Professor", impostor: "Diretor" },
    { civilian: "Advogado", impostor: "Juiz" },
    { civilian: "Pintor", impostor: "Escultor" },
    { civilian: "Cozinheiro", impostor: "Padeiro" },
    { civilian: "Cantor", impostor: "Ator" },
    { civilian: "Astronauta", impostor: "Piloto" },
    { civilian: "Programador", impostor: "Designer" },
    { civilian: "Dentista", impostor: "Ortodontista" },
    { civilian: "Arquiteto", impostor: "Engenheiro" },
    { civilian: "Fotógrafo", impostor: "Cinegrafista" },
    { civilian: "Veterinário", impostor: "Biólogo" },
    { civilian: "Eletricista", impostor: "Encanador" },
    { civilian: "Carteiro", impostor: "Entregador" },
    { civilian: "Jornalista", impostor: "Escritor" },
    { civilian: "Costureiro", impostor: "Estilista" },
    { civilian: "Psicólogo", impostor: "Psiquiatra" },
    { civilian: "Mecânico", impostor: "Funileiro" },
    { civilian: "Faxineiro", impostor: "Jardineiro" }
  ],
  "Objetos do Cotidiano": [
    { civilian: "Caneta", impostor: "Lápis" },
    { civilian: "Computador", impostor: "Celular" },
    { civilian: "Relógio", impostor: "Cronômetro" },
    { civilian: "Guarda-chuva", impostor: "Capa de chuva" },
    { civilian: "Cama", impostor: "Sofá" },
    { civilian: "Óculos", impostor: "Lupa" },
    { civilian: "Livro", impostor: "Caderno" },
    { civilian: "Chave", impostor: "Cadeado" },
    { civilian: "Escova de Dentes", impostor: "Fio Dental" },
    { civilian: "Copo", impostor: "Caneca" },
    { civilian: "Garfo", impostor: "Faca" },
    { civilian: "Espelho", impostor: "Quadro" },
    { civilian: "Mochila", impostor: "Mala" },
    { civilian: "Travesseiro", impostor: "Almofada" },
    { civilian: "Sabonete", impostor: "Shampoo" },
    { civilian: "Lixeira", impostor: "Balde" },
    { civilian: "Lanterna", impostor: "Vela" },
    { civilian: "Martelo", impostor: "Alicate" },
    { civilian: "Prato", impostor: "Tigela" },
    { civilian: "Bateria", impostor: "Carregador" }
  ],
  "Esportes e Lazer": [
    { civilian: "Futebol", impostor: "Futsal" },
    { civilian: "Basquete", impostor: "Vôlei" },
    { civilian: "Tênis", impostor: "Pingue-pongue" },
    { civilian: "Natação", impostor: "Surf" },
    { civilian: "Corrida", impostor: "Caminhada" },
    { civilian: "Boxe", impostor: "Caratê" },
    { civilian: "Ciclismo", impostor: "Motociclismo" },
    { civilian: "Dança", impostor: "Ballet" },
    { civilian: "Xadrez", impostor: "Damas" },
    { civilian: "Videogame", impostor: "Jogo de Tabuleiro" },
    { civilian: "Skate", impostor: "Patinete" },
    { civilian: "Escalada", impostor: "Rapel" },
    { civilian: "Poker", impostor: "Blackjack" },
    { civilian: "Musculação", impostor: "Crossfit" },
    { civilian: "Yoga", impostor: "Pilates" },
    { civilian: "Boliche", impostor: "Sinuca" },
    { civilian: "Acampar", impostor: "Piquenique" },
    { civilian: "Cantar", impostor: "Tocar Instrumento" },
    { civilian: "Desenhar", impostor: "Pintar" },
    { civilian: "Pescaria", impostor: "Caça" }
  ],
  "Cultura e Tecnologia": [
    { civilian: "Netflix", impostor: "YouTube" },
    { civilian: "WhatsApp", impostor: "Telegram" },
    { civilian: "Instagram", impostor: "TikTok" },
    { civilian: "Marvel", impostor: "DC" },
    { civilian: "Star Wars", impostor: "Star Trek" },
    { civilian: "Google", impostor: "Bing" },
    { civilian: "Windows", impostor: "Linux" },
    { civilian: "Wi-Fi", impostor: "Bluetooth" },
    { civilian: "Cinema", impostor: "Streaming" },
    { civilian: "Desenho Animado", impostor: "Anime" },
    { civilian: "E-mail", impostor: "Mensagem SMS" },
    { civilian: "Fone de Ouvido", impostor: "Caixa de Som" },
    { civilian: "Teclado", impostor: "Mouse" },
    { civilian: "PlayStation", impostor: "Xbox" },
    { civilian: "Fotografia", impostor: "Pintura" }
  ],
  "Informatica": [
    { civilian: "Computador", impostor: "Notebook" },
    { civilian: "Arquivo", impostor: "Pasta" },
    { civilian: "Download", impostor: "Upload" },
    { civilian: "Sistema Operacional", impostor: "Programa" },
    { civilian: "Desktop", impostor: "Area de Trabalho" },
    { civilian: "Navegador", impostor: "Aplicativo" },
    { civilian: "Planilha", impostor: "Documento" },
    { civilian: "Atalho", impostor: "Icone" },
    { civilian: "Backup", impostor: "Sincronizacao" },
    { civilian: "Instalador", impostor: "Atualizador" },
    { civilian: "Login", impostor: "Cadastro" },
    { civilian: "Senha", impostor: "PIN" },
    { civilian: "Lixeira", impostor: "Excluir" },
    { civilian: "Print Screen", impostor: "Captura de Tela" },
    { civilian: "Modo Escuro", impostor: "Modo Claro" }
  ],
  "Hardware": [
    { civilian: "Processador", impostor: "Placa-Mae" },
    { civilian: "Memoria RAM", impostor: "SSD" },
    { civilian: "Placa de Video", impostor: "Placa de Captura" },
    { civilian: "Fonte", impostor: "Estabilizador" },
    { civilian: "Cooler", impostor: "Water Cooler" },
    { civilian: "HD", impostor: "SSD" },
    { civilian: "Gabinete", impostor: "Rack" },
    { civilian: "Monitor", impostor: "Tela" },
    { civilian: "Teclado", impostor: "Mouse" },
    { civilian: "Webcam", impostor: "Microfone" },
    { civilian: "Headset", impostor: "Fone de Ouvido" },
    { civilian: "Cabo HDMI", impostor: "Cabo DisplayPort" },
    { civilian: "USB", impostor: "USB-C" },
    { civilian: "Impressora", impostor: "Scanner" },
    { civilian: "Roteador", impostor: "Modem" }
  ],
  "Programacao": [
    { civilian: "JavaScript", impostor: "TypeScript" },
    { civilian: "HTML", impostor: "CSS" },
    { civilian: "React", impostor: "Vue" },
    { civilian: "Node.js", impostor: "Deno" },
    { civilian: "Python", impostor: "Ruby" },
    { civilian: "Java", impostor: "C#" },
    { civilian: "Funcao", impostor: "Metodo" },
    { civilian: "Variavel", impostor: "Constante" },
    { civilian: "Array", impostor: "Lista" },
    { civilian: "Objeto", impostor: "Classe" },
    { civilian: "Bug", impostor: "Erro" },
    { civilian: "Commit", impostor: "Push" },
    { civilian: "Branch", impostor: "Merge" },
    { civilian: "API", impostor: "Endpoint" },
    { civilian: "Banco de Dados", impostor: "Tabela" }
  ],
  "Redes e Internet": [
    { civilian: "Wi-Fi", impostor: "Bluetooth" },
    { civilian: "Roteador", impostor: "Modem" },
    { civilian: "IP", impostor: "DNS" },
    { civilian: "Servidor", impostor: "Cliente" },
    { civilian: "HTTP", impostor: "HTTPS" },
    { civilian: "Ping", impostor: "Latencia" },
    { civilian: "Download", impostor: "Streaming" },
    { civilian: "Ethernet", impostor: "Fibra Optica" },
    { civilian: "Nuvem", impostor: "Data Center" },
    { civilian: "Domínio", impostor: "Hospedagem" },
    { civilian: "Firewall", impostor: "Proxy" },
    { civilian: "VPN", impostor: "DNS Privado" },
    { civilian: "Link", impostor: "URL" },
    { civilian: "Cookie", impostor: "Cache" },
    { civilian: "Site", impostor: "Portal" }
  ],
  "Seguranca Digital": [
    { civilian: "Antivirus", impostor: "Firewall" },
    { civilian: "Senha Forte", impostor: "Autenticacao em Dois Fatores" },
    { civilian: "Phishing", impostor: "Golpe Online" },
    { civilian: "Malware", impostor: "Virus" },
    { civilian: "Ransomware", impostor: "Spyware" },
    { civilian: "Criptografia", impostor: "Hash" },
    { civilian: "Backup", impostor: "Restauracao" },
    { civilian: "Token", impostor: "Codigo de Verificacao" },
    { civilian: "Login Suspeito", impostor: "Acesso Bloqueado" },
    { civilian: "Permissao", impostor: "Privilegio" },
    { civilian: "Vazamento de Dados", impostor: "Roubo de Senha" },
    { civilian: "Modo Anonimo", impostor: "VPN" },
    { civilian: "Biometria", impostor: "Reconhecimento Facial" },
    { civilian: "Chave de Acesso", impostor: "Certificado Digital" },
    { civilian: "Atualizacao de Seguranca", impostor: "Correcao de Bug" }
  ],
  "Jogos Eletronicos": [
    { civilian: "Minecraft", impostor: "Terraria" },
    { civilian: "Fortnite", impostor: "PUBG" },
    { civilian: "Valorant", impostor: "Counter-Strike" },
    { civilian: "League of Legends", impostor: "Dota 2" },
    { civilian: "FIFA", impostor: "eFootball" },
    { civilian: "GTA", impostor: "Watch Dogs" },
    { civilian: "The Sims", impostor: "Animal Crossing" },
    { civilian: "Roblox", impostor: "Minecraft" },
    { civilian: "Mario Kart", impostor: "Crash Team Racing" },
    { civilian: "Zelda", impostor: "Elden Ring" },
    { civilian: "God of War", impostor: "Devil May Cry" },
    { civilian: "Resident Evil", impostor: "Silent Hill" },
    { civilian: "Among Us", impostor: "Town of Salem" },
    { civilian: "Rocket League", impostor: "Trackmania" },
    { civilian: "Call of Duty", impostor: "Battlefield" }
  ],
  "Cinema e Filmes": [
    { civilian: "Titanic", impostor: "Diario de uma Paixao" },
    { civilian: "Vingadores", impostor: "Liga da Justica" },
    { civilian: "Harry Potter", impostor: "Senhor dos Aneis" },
    { civilian: "Star Wars", impostor: "Star Trek" },
    { civilian: "Jurassic Park", impostor: "Godzilla" },
    { civilian: "Matrix", impostor: "Blade Runner" },
    { civilian: "Avatar", impostor: "Planeta dos Macacos" },
    { civilian: "Velozes e Furiosos", impostor: "Need for Speed" },
    { civilian: "Toy Story", impostor: "Monstros S.A." },
    { civilian: "Homem-Aranha", impostor: "Batman" },
    { civilian: "Coringa", impostor: "Taxi Driver" },
    { civilian: "Invocacao do Mal", impostor: "Sobrenatural" },
    { civilian: "Interestelar", impostor: "Gravidade" },
    { civilian: "Panico", impostor: "Halloween" },
    { civilian: "Missao Impossivel", impostor: "007" }
  ],
  "Desenhos": [
    { civilian: "Bob Esponja", impostor: "Patrick" },
    { civilian: "Pica-Pau", impostor: "Pernalonga" },
    { civilian: "Tom e Jerry", impostor: "Looney Tunes" },
    { civilian: "Os Simpsons", impostor: "Family Guy" },
    { civilian: "Ben 10", impostor: "Mutante Rex" },
    { civilian: "Hora de Aventura", impostor: "Steven Universo" },
    { civilian: "Gravity Falls", impostor: "A Casa Coruja" },
    { civilian: "Scooby-Doo", impostor: "Coragem" },
    { civilian: "Pokemon", impostor: "Digimon" },
    { civilian: "Naruto", impostor: "Dragon Ball" },
    { civilian: "Avatar", impostor: "Korra" },
    { civilian: "Peppa Pig", impostor: "Dora Aventureira" },
    { civilian: "Jovens Titas", impostor: "Liga da Justica" },
    { civilian: "Phineas e Ferb", impostor: "Kim Possible" },
    { civilian: "As Meninas Superpoderosas", impostor: "Tres Espias Demais" }
  ],
  "Marcas": [
    { civilian: "Nike", impostor: "Adidas" },
    { civilian: "Coca-Cola", impostor: "Pepsi" },
    { civilian: "Apple", impostor: "Samsung" },
    { civilian: "McDonald's", impostor: "Burger King" },
    { civilian: "Netflix", impostor: "Prime Video" },
    { civilian: "Spotify", impostor: "Deezer" },
    { civilian: "PlayStation", impostor: "Xbox" },
    { civilian: "Google", impostor: "Microsoft" },
    { civilian: "Instagram", impostor: "TikTok" },
    { civilian: "Uber", impostor: "99" },
    { civilian: "iFood", impostor: "Rappi" },
    { civilian: "Nubank", impostor: "Inter" },
    { civilian: "Amazon", impostor: "Mercado Livre" },
    { civilian: "Lacoste", impostor: "Polo Ralph Lauren" },
    { civilian: "Puma", impostor: "New Balance" }
  ],
  "Comida": [
    { civilian: "Pizza", impostor: "Esfiha" },
    { civilian: "Hamburguer", impostor: "X-Bacon" },
    { civilian: "Coxinha", impostor: "Risole" },
    { civilian: "Pastel", impostor: "Empada" },
    { civilian: "Lasanha", impostor: "Nhoque" },
    { civilian: "Macarrao", impostor: "Yakissoba" },
    { civilian: "Churrasco", impostor: "Espetinho" },
    { civilian: "Feijoada", impostor: "Dobradinha" },
    { civilian: "Sushi", impostor: "Temaki" },
    { civilian: "Taco", impostor: "Burrito" },
    { civilian: "Panqueca", impostor: "Crepe" },
    { civilian: "Bolo", impostor: "Cupcake" },
    { civilian: "Pudim", impostor: "Mousse" },
    { civilian: "Sorvete", impostor: "Acai" },
    { civilian: "Pipoca", impostor: "Nachos" }
  ],
  "Piadas Ruins": [
    { civilian: "Trocadilho", impostor: "Piada de Tiozao" },
    { civilian: "Pave", impostor: "Pacume" },
    { civilian: "Humor Seco", impostor: "Ironia" },
    { civilian: "Piada Interna", impostor: "Memoria Vergonhosa" },
    { civilian: "Silencio Constrangedor", impostor: "Riso Forcado" },
    { civilian: "Vergonha Alheia", impostor: "Mico" },
    { civilian: "Cantada Ruim", impostor: "Xaveco Fraco" },
    { civilian: "Meme Antigo", impostor: "Audio Estourado" },
    { civilian: "Pegadinha", impostor: "Trollagem" },
    { civilian: "Resposta Atravessada", impostor: "Corte Seco" },
    { civilian: "Deboche", impostor: "Sarcasmo" },
    { civilian: "Piada Sem Graca", impostor: "Comentário Infeliz" },
    { civilian: "Climao", impostor: "Saia Justa" },
    { civilian: "Rir de Nervoso", impostor: "Disfarcar o Riso" },
    { civilian: "Historia Mal Contada", impostor: "Desculpa Esfarrapada" }
  ],
  "Duplo Sentido": [
    { civilian: "Banana", impostor: "Pepino" },
    { civilian: "Linguiça", impostor: "Salsicha" },
    { civilian: "Manga", impostor: "Melancia" },
    { civilian: "Pau de Selfie", impostor: "Tripé" },
    { civilian: "Entrar", impostor: "Sair" },
    { civilian: "Subir", impostor: "Descer" },
    { civilian: "Molhado", impostor: "Escorregadio" },
    { civilian: "Quente", impostor: "Pegando Fogo" },
    { civilian: "Apertado", impostor: "Justo" },
    { civilian: "Grande", impostor: "Enorme" },
    { civilian: "Pequeno", impostor: "Miudo" },
    { civilian: "Bater", impostor: "Mexer" },
    { civilian: "Encaixar", impostor: "Empurrar" },
    { civilian: "Furar", impostor: "Espetar" },
    { civilian: "Amassar", impostor: "Apertar" }
  ],
  "Tretas e Constrangimentos": [
    { civilian: "Fofoca", impostor: "Boato" },
    { civilian: "Exposed", impostor: "Print Vazado" },
    { civilian: "Visto por Ultimo", impostor: "Mensagem Visualizada" },
    { civilian: "Grupo Silenciado", impostor: "Mensagem Ignorada" },
    { civilian: "Cancelamento", impostor: "Critica Pesada" },
    { civilian: "Discussao de Familia", impostor: "Almoco de Domingo" },
    { civilian: "DR", impostor: "Conversa Seria" },
    { civilian: "Amizade Colorida", impostor: "Crush Secreto" },
    { civilian: "Conta Dividida", impostor: "Pix Esquecido" },
    { civilian: "Chegar Atrasado", impostor: "Furar o Role" },
    { civilian: "Mentira Pequena", impostor: "Desculpa Ruim" },
    { civilian: "Segredo Vazado", impostor: "Conversa Printada" },
    { civilian: "Olhar Torto", impostor: "Indireta" },
    { civilian: "Ciúmes", impostor: "Desconfiança" },
    { civilian: "Clima Pesado", impostor: "Silencio Estranho" }
  ]
};

// Retorna uma lista de todas as categorias disponíveis
export const getCategories = () => Object.keys(wordCategories);

// Seleciona um par de palavras aleatório baseado na categoria fornecida.
// Se a categoria for "Aleatório" ou inexistente, escolhe uma categoria aleatória.
export function getRandomPair(category) {
  let selectedCategory = category;
  const categories = getCategories();
  
  if (!category || category === "Aleatório" || !wordCategories[category]) {
    selectedCategory = categories[Math.floor(Math.random() * categories.length)];
  }
  
  const list = wordCategories[selectedCategory];
  const pair = list[Math.floor(Math.random() * list.length)];
  return {
    category: selectedCategory,
    ...pair
  };
}
