// Banco de dados de palavras para o jogo IMPOSTOR.
// Cada categoria possui pares de palavras fortemente relacionadas para que o impostor possa blefar sutilmente.

export const wordCategories = {
  "Alimentos e Bebidas": [
    { civilian: "Pizza", impostor: "Hambúrguer" },
    { civilian: "Café", impostor: "Chá" },
    { civilian: "Cerveja", impostor: "Vinho" },
    { civilian: "Sorvete", impostor: "Picolé" },
    { civilian: "Sushi", impostor: "Sashimi" },
    { civilian: "Chocolate", impostor: "Brigadeiro" },
    { civilian: "Pão", impostor: "Torrada" },
    { civilian: "Arroz", impostor: "Feijão" },
    { civilian: "Maçã", impostor: "Pera" },
    { civilian: "Refrigerante", impostor: "Suco" },
    { civilian: "Queijo", impostor: "Presunto" },
    { civilian: "Coxinha", impostor: "Pastel" },
    { civilian: "Lasanha", impostor: "Macarronada" },
    { civilian: "Bolo", impostor: "Torta" },
    { civilian: "Pipoca", impostor: "Algodão Doce" },
    { civilian: "Leite", impostor: "Iogurte" },
    { civilian: "Melancia", impostor: "Melão" },
    { civilian: "Biscoito", impostor: "Bolacha" },
    { civilian: "Batata Frita", impostor: "Purê de Batata" },
    { civilian: "Pudim", impostor: "Gelatina" }
  ],
  "Animais": [
    { civilian: "Cão", impostor: "Gato" },
    { civilian: "Leão", impostor: "Tigre" },
    { civilian: "Golfinho", impostor: "Baleia" },
    { civilian: "Cavalo", impostor: "Zebra" },
    { civilian: "Águia", impostor: "Gavião" },
    { civilian: "Rato", impostor: "Hamster" },
    { civilian: "Jacaré", impostor: "Crocodilo" },
    { civilian: "Abelha", impostor: "Vespa" },
    { civilian: "Elefante", impostor: "Mamute" },
    { civilian: "Tubarão", impostor: "Arraia" },
    { civilian: "Macaco", impostor: "Gorila" },
    { civilian: "Pinguim", impostor: "Ganso" },
    { civilian: "Cobra", impostor: "Lagarto" },
    { civilian: "Formiga", impostor: "Cupim" },
    { civilian: "Coruja", impostor: "Morcego" },
    { civilian: "Urso", impostor: "Panda" },
    { civilian: "Galinha", impostor: "Pato" },
    { civilian: "Sapo", impostor: "Rã" },
    { civilian: "Ovelha", impostor: "Cabra" },
    { civilian: "Caranguejo", impostor: "Lagosta" }
  ],
  "Lugares e Turismo": [
    { civilian: "Praia", impostor: "Piscina" },
    { civilian: "Cinema", impostor: "Teatro" },
    { civilian: "Escola", impostor: "Faculdade" },
    { civilian: "Hospital", impostor: "Posto de Saúde" },
    { civilian: "Parque", impostor: "Floresta" },
    { civilian: "Shopping", impostor: "Supermercado" },
    { civilian: "Academia", impostor: "Estádio" },
    { civilian: "Aeroporto", impostor: "Rodoviária" },
    { civilian: "Museu", impostor: "Biblioteca" },
    { civilian: "Hotel", impostor: "Pousada" },
    { civilian: "Igreja", impostor: "Templo" },
    { civilian: "Escritório", impostor: "Home Office" },
    { civilian: "Restaurante", impostor: "Lanchonete" },
    { civilian: "Zoológico", impostor: "Aquário" },
    { civilian: "Castelo", impostor: "Palácio" },
    { civilian: "Fazenda", impostor: "Sítio" },
    { civilian: "Cachoeira", impostor: "Rio" },
    { civilian: "Padaria", impostor: "Confeitaria" },
    { civilian: "Montanha", impostor: "Vulcão" },
    { civilian: "Metrô", impostor: "Trem" }
  ],
  "Profissões": [
    { civilian: "Médico", impostor: "Enfermeiro" },
    { civilian: "Bombeiro", impostor: "Policial" },
    { civilian: "Professor", impostor: "Diretor" },
    { civilian: "Advogado", impostor: "Juiz" },
    { civilian: "Pintor", impostor: "Escultor" },
    { civilian: "Cozinheiro", impostor: "Padeiro" },
    { civilian: "Cantor", impostor: "Ator" },
    { civilian: "Astronauta", impostor: "Piloto" },
    { civilian: "Programador", impostor: "Designer" },
    { civilian: "Dentista", impostor: "Ortodontista" },
    { civilian: "Arquiteto", impostor: "Engenheiro" },
    { civilian: "Fotógrafo", impostor: "Cinegrafista" },
    { civilian: "Veterinário", impostor: "Biólogo" },
    { civilian: "Eletricista", impostor: "Encanador" },
    { civilian: "Carteiro", impostor: "Entregador" },
    { civilian: "Jornalista", impostor: "Escritor" },
    { civilian: "Costureiro", impostor: "Estilista" },
    { civilian: "Psicólogo", impostor: "Psiquiatra" },
    { civilian: "Mecânico", impostor: "Funileiro" },
    { civilian: "Faxineiro", impostor: "Jardineiro" }
  ],
  "Objetos do Cotidiano": [
    { civilian: "Caneta", impostor: "Lápis" },
    { civilian: "Computador", impostor: "Celular" },
    { civilian: "Relógio", impostor: "Cronômetro" },
    { civilian: "Guarda-chuva", impostor: "Capa de chuva" },
    { civilian: "Cama", impostor: "Sofá" },
    { civilian: "Óculos", impostor: "Lupa" },
    { civilian: "Livro", impostor: "Caderno" },
    { civilian: "Chave", impostor: "Cadeado" },
    { civilian: "Escova de Dentes", impostor: "Fio Dental" },
    { civilian: "Copo", impostor: "Caneca" },
    { civilian: "Garfo", impostor: "Faca" },
    { civilian: "Espelho", impostor: "Quadro" },
    { civilian: "Mochila", impostor: "Mala" },
    { civilian: "Travesseiro", impostor: "Almofada" },
    { civilian: "Sabonete", impostor: "Shampoo" },
    { civilian: "Lixeira", impostor: "Balde" },
    { civilian: "Lanterna", impostor: "Vela" },
    { civilian: "Martelo", impostor: "Alicate" },
    { civilian: "Prato", impostor: "Tigela" },
    { civilian: "Bateria", impostor: "Carregador" }
  ],
  "Esportes e Lazer": [
    { civilian: "Futebol", impostor: "Futsal" },
    { civilian: "Basquete", impostor: "Vôlei" },
    { civilian: "Tênis", impostor: "Pingue-pongue" },
    { civilian: "Natação", impostor: "Surf" },
    { civilian: "Corrida", impostor: "Caminhada" },
    { civilian: "Boxe", impostor: "Caratê" },
    { civilian: "Ciclismo", impostor: "Motociclismo" },
    { civilian: "Dança", impostor: "Ballet" },
    { civilian: "Xadrez", impostor: "Damas" },
    { civilian: "Videogame", impostor: "Jogo de Tabuleiro" },
    { civilian: "Skate", impostor: "Patinete" },
    { civilian: "Escalada", impostor: "Rapel" },
    { civilian: "Poker", impostor: "Blackjack" },
    { civilian: "Musculação", impostor: "Crossfit" },
    { civilian: "Yoga", impostor: "Pilates" },
    { civilian: "Boliche", impostor: "Sinuca" },
    { civilian: "Acampar", impostor: "Piquenique" },
    { civilian: "Cantar", impostor: "Tocar Instrumento" },
    { civilian: "Desenhar", impostor: "Pintar" },
    { civilian: "Pescaria", impostor: "Caça" }
  ],
  "Cultura e Tecnologia": [
    { civilian: "Netflix", impostor: "YouTube" },
    { civilian: "WhatsApp", impostor: "Telegram" },
    { civilian: "Instagram", impostor: "TikTok" },
    { civilian: "Marvel", impostor: "DC" },
    { civilian: "Star Wars", impostor: "Star Trek" },
    { civilian: "Google", impostor: "Bing" },
    { civilian: "Windows", impostor: "Linux" },
    { civilian: "Wi-Fi", impostor: "Bluetooth" },
    { civilian: "Cinema", impostor: "Streaming" },
    { civilian: "Desenho Animado", impostor: "Anime" },
    { civilian: "E-mail", impostor: "Mensagem SMS" },
    { civilian: "Fone de Ouvido", impostor: "Caixa de Som" },
    { civilian: "Teclado", impostor: "Mouse" },
    { civilian: "PlayStation", impostor: "Xbox" },
    { civilian: "Fotografia", impostor: "Pintura" }
  ],
  "Informatica": [
    { civilian: "Computador", impostor: "Notebook" },
    { civilian: "Arquivo", impostor: "Pasta" },
    { civilian: "Download", impostor: "Upload" },
    { civilian: "Sistema Operacional", impostor: "Programa" },
    { civilian: "Desktop", impostor: "Area de Trabalho" },
    { civilian: "Navegador", impostor: "Aplicativo" },
    { civilian: "Planilha", impostor: "Documento" },
    { civilian: "Atalho", impostor: "Icone" },
    { civilian: "Backup", impostor: "Sincronizacao" },
    { civilian: "Instalador", impostor: "Atualizador" },
    { civilian: "Login", impostor: "Cadastro" },
    { civilian: "Senha", impostor: "PIN" },
    { civilian: "Lixeira", impostor: "Excluir" },
    { civilian: "Print Screen", impostor: "Captura de Tela" },
    { civilian: "Modo Escuro", impostor: "Modo Claro" }
  ],
  "Hardware": [
    { civilian: "Processador", impostor: "Placa-Mae" },
    { civilian: "Memoria RAM", impostor: "SSD" },
    { civilian: "Placa de Video", impostor: "Placa de Captura" },
    { civilian: "Fonte", impostor: "Estabilizador" },
    { civilian: "Cooler", impostor: "Water Cooler" },
    { civilian: "HD", impostor: "SSD" },
    { civilian: "Gabinete", impostor: "Rack" },
    { civilian: "Monitor", impostor: "Tela" },
    { civilian: "Teclado", impostor: "Mouse" },
    { civilian: "Webcam", impostor: "Microfone" },
    { civilian: "Headset", impostor: "Fone de Ouvido" },
    { civilian: "Cabo HDMI", impostor: "Cabo DisplayPort" },
    { civilian: "USB", impostor: "USB-C" },
    { civilian: "Impressora", impostor: "Scanner" },
    { civilian: "Roteador", impostor: "Modem" }
  ],
  "Programacao": [
    { civilian: "JavaScript", impostor: "TypeScript" },
    { civilian: "HTML", impostor: "CSS" },
    { civilian: "React", impostor: "Vue" },
    { civilian: "Node.js", impostor: "Deno" },
    { civilian: "Python", impostor: "Ruby" },
    { civilian: "Java", impostor: "C#" },
    { civilian: "Funcao", impostor: "Metodo" },
    { civilian: "Variavel", impostor: "Constante" },
    { civilian: "Array", impostor: "Lista" },
    { civilian: "Objeto", impostor: "Classe" },
    { civilian: "Bug", impostor: "Erro" },
    { civilian: "Commit", impostor: "Push" },
    { civilian: "Branch", impostor: "Merge" },
    { civilian: "API", impostor: "Endpoint" },
    { civilian: "Banco de Dados", impostor: "Tabela" }
  ],
  "Redes e Internet": [
    { civilian: "Wi-Fi", impostor: "Bluetooth" },
    { civilian: "Roteador", impostor: "Modem" },
    { civilian: "IP", impostor: "DNS" },
    { civilian: "Servidor", impostor: "Cliente" },
    { civilian: "HTTP", impostor: "HTTPS" },
    { civilian: "Ping", impostor: "Latencia" },
    { civilian: "Download", impostor: "Streaming" },
    { civilian: "Ethernet", impostor: "Fibra Optica" },
    { civilian: "Nuvem", impostor: "Data Center" },
    { civilian: "Domínio", impostor: "Hospedagem" },
    { civilian: "Firewall", impostor: "Proxy" },
    { civilian: "VPN", impostor: "DNS Privado" },
    { civilian: "Link", impostor: "URL" },
    { civilian: "Cookie", impostor: "Cache" },
    { civilian: "Site", impostor: "Portal" }
  ],
  "Seguranca Digital": [
    { civilian: "Antivirus", impostor: "Firewall" },
    { civilian: "Senha Forte", impostor: "Autenticacao em Dois Fatores" },
    { civilian: "Phishing", impostor: "Golpe Online" },
    { civilian: "Malware", impostor: "Virus" },
    { civilian: "Ransomware", impostor: "Spyware" },
    { civilian: "Criptografia", impostor: "Hash" },
    { civilian: "Backup", impostor: "Restauracao" },
    { civilian: "Token", impostor: "Codigo de Verificacao" },
    { civilian: "Login Suspeito", impostor: "Acesso Bloqueado" },
    { civilian: "Permissao", impostor: "Privilegio" },
    { civilian: "Vazamento de Dados", impostor: "Roubo de Senha" },
    { civilian: "Modo Anonimo", impostor: "VPN" },
    { civilian: "Biometria", impostor: "Reconhecimento Facial" },
    { civilian: "Chave de Acesso", impostor: "Certificado Digital" },
    { civilian: "Atualizacao de Seguranca", impostor: "Correcao de Bug" }
  ]
};

// Retorna uma lista de todas as categorias disponíveis
export const getCategories = () => Object.keys(wordCategories);

// Seleciona um par de palavras aleatório baseado na categoria fornecida.
// Se a categoria for "Aleatório" ou inexistente, escolhe uma categoria aleatória.
export function getRandomPair(category) {
  let selectedCategory = category;
  const categories = getCategories();
  
  if (!category || category === "Aleatório" || !wordCategories[category]) {
    selectedCategory = categories[Math.floor(Math.random() * categories.length)];
  }
  
  const list = wordCategories[selectedCategory];
  const pair = list[Math.floor(Math.random() * list.length)];
  return {
    category: selectedCategory,
    ...pair
  };
}
